### ISSUE TITLE
"Seprarate categories tabs" does work no more

### ISSUE THREAD

**Issue by synthview** [carrois/Kernkraft#13]
Hello,
on the last versions of Glyphs (Version 2.5b) the "Seprarate categories tabs" option opens only the 1st tab (letter); others do not open.

All best

**Comment by Mark2Mark** [comment]
Hi @synthview can you please tell me what’s written in the Macro Panel after it opens only that one tab? Thanks!

**Comment by synthview** [comment]
sure


Traceback (most recent call last):
  File "/Users/xxxxxxxx/Library/Application Support/Glyphs/Plugins/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 1364, in submitButtonCallback
    self.parent.generateTabOutput(actualInputGlyphName) # first main run
  File "/Users/xxxxxxxx/Library/Application Support/Glyphs/Plugins/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 902, in generateTabOutput
    self.makeTab(tabOutput)
  File "/Users/xxxxxxxx/Library/Application Support/Glyphs/Plugins/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 570, in makeTab
    self.setupTab()
  File "/Users/xxxxxxxx/Library/Application Support/Glyphs/Plugins/Kernkraft.glyphsPlugin/Contents/Resources/KernKraftModule.py", line 543, in setupTab
    location = len( ContentView.textStorage().string() ) -6  # len of rightTail
AttributeError: 'NSKVONotifying_GSTextStorage' object has no attribute 'string'

**Comment by Mark2Mark** [comment]
Thanks for reporting.

I cannot reproduce it with Build 1060. I think that is currently the lastet stable version, could you please try with that one?

Also getting @schriftgestalt into the conversation, `AttributeError: 'NSKVONotifying_GSTextStorage' object has no attribute 'string'` seems to be introduced in one of the newest betas of Glyphs?!

**Comment by synthview** [comment]
Yep, I’m using Version 2.5b (1073)

**Comment by schriftgestalt** [comment]
We changed the structure of the text system a bit. You need to change `location = len( ContentView.textStorage().string() )` to `location = len( ContentView.textStorage().text() )`. It will work in both, 2.4 and 2.5.

**Comment by Mark2Mark** [comment]
Thank you! @schriftgestalt 👏

@synthview I uploaded the fix, should be working after a Glyphs restart. Please confirm.

**Comment by synthview** [comment]
It works! thanks :)
